--- 
- hosts: all
  become: yes
  user: ansible
  connection: ssh

  tasks:
       - name : install httpd
         action: yum name=httpd state=installed
         notify: service start httpd

  handlers:         

       - name: service start httpd
         action: service name=httpd state=started  
